name: Сборка проектов

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-webpack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Сборка Webpack
        run: |
          cd webpack-project
          npm ci
          npm run build
      - name: Сохранение артефактов
        uses: actions/upload-artifact@v4
        with:
          name: webpack-build
          path: webpack-project/dist

  build-vite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '20'   # <-- важно для Vite
      - name: Сборка Vite
        run: |
          cd vite-project
          npm ci
          npm run build
      - name: Сохранение артефактов
        uses: actions/upload-artifact@v4
        with:
          name: vite-build
          path: vite-project/dist